services:
  radicale:
    image: tomsquest/docker-radicale
    container_name: radicale
    networks:
      - trusted_proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    volumes:
      - data:/data

  backup:
    image: offen/docker-volume-backup:latest
    restart: always
    env_file: ${BACKUP_PATH}/.env
    volumes:
      - data:/backup/my-app-backup:ro
      - ${BACKUP_PATH}:/archive

networks:
  trusted_proxy:
    external: true

volumes:
  data:
